#**Brazilian E-Commerce Public Dataset by Olist**

In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("olistbr/brazilian-ecommerce")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'brazilian-ecommerce' dataset.
Path to dataset files: /kaggle/input/brazilian-ecommerce

In [ ]:
import os

csv_files = [f for f in os.listdir(path) if f.endswith('.csv')]

print("Identified CSV files:", csv_files)

Identified CSV files: ['olist_customers_dataset.csv', 'olist_sellers_dataset.csv', 'olist_order_reviews_dataset.csv', 'olist_order_items_dataset.csv', 'olist_products_dataset.csv', 'olist_geolocation_dataset.csv', 'product_category_name_translation.csv', 'olist_orders_dataset.csv', 'olist_order_payments_dataset.csv']

In [ ]:
import pandas as pd
import numpy as np
# Olist Brazilian E-Commerce Datasets
# fixing all the imports

# Load Olist datasets (consistent f-string format)
customers = pd.read_csv(f'{path}/olist_customers_dataset.csv')
sellers = pd.read_csv(f'{path}/olist_sellers_dataset.csv')
order_reviews = pd.read_csv(f'{path}/olist_order_reviews_dataset.csv')
order_items = pd.read_csv(f'{path}/olist_order_items_dataset.csv')
products = pd.read_csv(f'{path}/olist_products_dataset.csv')
geolocation = pd.read_csv(f'{path}/olist_geolocation_dataset.csv')
category_translation = pd.read_csv(f'{path}/product_category_name_translation.csv')
orders = pd.read_csv(f'{path}/olist_orders_dataset.csv')
order_payments = pd.read_csv(f'{path}/olist_order_payments_dataset.csv')


print("Datasets loaded:")
print(f"- Customers: {len(customers)} rows")
print(f"- Sellers: {len(sellers)} rows")
print(f"- Order Reviews: {len(order_reviews)} rows")
print(f"- Order Items: {len(order_items)} rows")
print(f"- Products: {len(products)} rows")
print(f"- Geolocation: {len(geolocation)} rows")
print(f"- Category Translation: {len(category_translation)} rows")
print(f"- Orders: {len(orders)} rows")
print(f"- Order Payments: {len(order_payments)} rows")

Datasets loaded:
- Customers: 99441 rows
- Sellers: 3095 rows
- Order Reviews: 99224 rows
- Order Items: 112650 rows
- Products: 32951 rows
- Geolocation: 1000163 rows
- Category Translation: 71 rows
- Orders: 99441 rows
- Order Payments: 103886 rows

#**PHASE 1 (CLEANING DATA)**

1. Customers table

In [ ]:
customers.head(3)

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP

In [ ]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB

In [ ]:
customers.isnull().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

2. Seller Table

In [ ]:
sellers.head(3)

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ

In [ ]:
sellers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   object
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   object
 3   seller_state            3095 non-null   object
dtypes: int64(1), object(3)
memory usage: 96.8+ KB

In [ ]:
sellers.isnull().sum()

seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

3. Orders Reviews Table

In [ ]:
order_reviews.head(3)

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24

In [ ]:
order_reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  object
 1   order_id                 99224 non-null  object
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  object
 4   review_comment_message   40977 non-null  object
 5   review_creation_date     99224 non-null  object
 6   review_answer_timestamp  99224 non-null  object
dtypes: int64(1), object(6)
memory usage: 5.3+ MB

In [ ]:
order_reviews.isnull().sum()

review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

In [ ]:
# Since the blank fields indicates no comments

order_reviews['review_comment_message'] = order_reviews['review_comment_message'].fillna('No comment')
order_reviews['review_comment_title'] = order_reviews['review_comment_title'].fillna("No title")

In [ ]:
order_reviews.isnull().sum()

review_id                  0
order_id                   0
review_score               0
review_comment_title       0
review_comment_message     0
review_creation_date       0
review_answer_timestamp    0
dtype: int64

4. Order Item Table

In [ ]:
order_items.head(3)

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.9,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.9,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.0,17.87

In [ ]:
order_items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  object
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 6.0+ MB

In [ ]:
order_items['shipping_limit_date'] = pd.to_datetime(order_items['shipping_limit_date'])

In [ ]:
order_items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  datetime64[ns]
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: datetime64[ns](1), float64(2), int64(1), object(3)
memory usage: 6.0+ MB

5. Products Table

In [ ]:
products.sample(3)

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
12609,5ab02ca028398131a5ae91401eb49788,esporte_lazer,33.0,1322.0,2.0,700.0,26.0,16.0,21.0
21858,44d097d59e8430f88a67517cd0c4f865,fashion_bolsas_e_acessorios,55.0,151.0,6.0,350.0,16.0,2.0,20.0
21396,b74d02ba43060d2cbeba7759a869da5e,perfumaria,60.0,863.0,4.0,1500.0,30.0,12.0,28.0

In [ ]:
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  object
 1   product_category_name       32341 non-null  object
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), object(2)
memory usage: 2.3+ MB

In [ ]:
products.rename(columns= {"product_name_lenght": "product_name_length", "product_description_lenght": "product_description_length"}, inplace =True)

In [ ]:
products.isnull().sum()

product_id                      0
product_category_name         610
product_name_length           610
product_description_length    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [ ]:

products['product_category_name'] = products['product_category_name'].fillna("Unknown")
products['product_name_length'] = products['product_name_length'].fillna(products['product_name_length'].mean())
products['product_description_length'] = products['product_description_length'].fillna(products['product_description_length'].mean())
products['product_photos_qty'] = products['product_photos_qty'].fillna(products['product_photos_qty'].mean())
products['product_weight_g'] = products['product_weight_g'].fillna(products['product_weight_g'].mean())
products['product_length_cm'] = products['product_length_cm'].fillna(products['product_length_cm'].mean())
products['product_height_cm'] = products['product_height_cm'].fillna(products['product_height_cm'].mean())
products['product_width_cm'] = products['product_width_cm'].fillna(products['product_width_cm'].mean())

In [ ]:
products.isnull().sum()

product_id                    0
product_category_name         0
product_name_length           0
product_description_length    0
product_photos_qty            0
product_weight_g              0
product_length_cm             0
product_height_cm             0
product_width_cm              0
dtype: int64

6. Geolocation Table

In [ ]:
geolocation.sample(3)

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
313784,13500,-22.400420,-47.566477,rio claro,SP
63438,3613,-23.519581,-46.533843,sao paulo,SP
122515,5210,-23.417851,-46.753944,sao paulo,SP

In [ ]:
geolocation.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   geolocation_zip_code_prefix  1000163 non-null  int64
 1   geolocation_lat              1000163 non-null  float64
 2   geolocation_lng              1000163 non-null  float64
 3   geolocation_city             1000163 non-null  object
 4   geolocation_state            1000163 non-null  object
dtypes: float64(2), int64(1), object(2)
memory usage: 38.2+ MB

In [ ]:
geolocation.isnull().sum()

geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

7. Translation Table

In [ ]:
category_translation.sample(3)

   product_category_name product_category_name_english
6             perfumaria                     perfumery
62       casa_conforto_2                home_comfort_2
2             automotivo                          auto

In [ ]:
category_translation.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_category_name          71 non-null     object
 1   product_category_name_english  71 non-null     object
dtypes: object(2)
memory usage: 1.2+ KB

In [ ]:
category_translation.isnull().sum()

product_category_name            0
product_category_name_english    0
dtype: int64

8. Order Table

In [ ]:
orders.sample(3)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
77429,22bd0b5dc9f8dbddd22aeab8ef27fd85,7d1e5179bc9a15bb041726618ed35d12,delivered,2018-06-19 10:08:49,2018-06-20 02:54:57,2018-06-21 14:31:00,2018-06-25 15:36:46,2018-07-16 00:00:00
57585,607d8f6570c73e6a2e553908d572abc7,9fe84c7ab94da8e3d39926676b4bd6b6,delivered,2017-10-28 21:35:13,2017-10-28 21:46:27,2017-10-30 20:48:28,2017-11-14 20:15:00,2017-11-27 00:00:00
5862,21265f499055fc933501ce3a66c1ef9a,0e0baf7742b23bc2ca9d12425f4d5928,delivered,2017-10-01 14:39:43,2017-10-01 14:56:07,2017-10-02 18:31:49,2017-10-05 19:48:34,2017-10-24 00:00:00

In [ ]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB

In [ ]:
orders['order_purchase_timestamp'] = pd.to_datetime(orders['order_purchase_timestamp'])
orders['order_approved_at'] = pd.to_datetime(orders['order_approved_at'])
orders['order_delivered_carrier_date'] = pd.to_datetime(orders['order_delivered_carrier_date'])
orders['order_delivered_customer_date'] = pd.to_datetime(orders['order_delivered_customer_date'])
orders['order_estimated_delivery_date'] = pd.to_datetime(orders['order_estimated_delivery_date'])

In [ ]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  datetime64[ns]
 4   order_approved_at              99281 non-null  datetime64[ns]
 5   order_delivered_carrier_date   97658 non-null  datetime64[ns]
 6   order_delivered_customer_date  96476 non-null  datetime64[ns]
 7   order_estimated_delivery_date  99441 non-null  datetime64[ns]
dtypes: datetime64[ns](5), object(3)
memory usage: 6.1+ MB

In [ ]:
orders.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [ ]:

avg_approval_time = (orders['order_approved_at'] - orders['order_purchase_timestamp']).mean()
avg_carrier_time = (orders['order_delivered_carrier_date'] - orders['order_approved_at']).mean()
avg_delivery_time = (orders['order_delivered_customer_date'] - orders['order_delivered_carrier_date']).mean()

orders['order_approved_at'] = orders['order_approved_at'].fillna(orders['order_purchase_timestamp'] + avg_approval_time)

orders['order_delivered_carrier_date'] = orders['order_delivered_carrier_date'].fillna(orders['order_approved_at'] + avg_carrier_time)

orders['order_delivered_customer_date'] = orders['order_delivered_customer_date'].fillna(orders['order_delivered_carrier_date'] + avg_delivery_time)

In [ ]:
orders.isnull().sum()

order_id                         0
customer_id                      0
order_status                     0
order_purchase_timestamp         0
order_approved_at                0
order_delivered_carrier_date     0
order_delivered_customer_date    0
order_estimated_delivery_date    0
dtype: int64

9. Order Payment Table

In [ ]:
order_payments.sample(3)

,order_id,payment_sequential,payment_type,payment_installments,payment_value
9852,2c42da58ddeeeffa46d6ddc5e6725e31,1,credit_card,2,96.65
23098,ad49f229e233b39202eb79fdc1877074,1,credit_card,2,36.70
99559,287a3634b689a3b876e3993e081bcc6b,2,voucher,1,200.91

In [ ]:
order_payments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  object
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  object
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.0+ MB

In [ ]:
order_payments.isnull().sum()

order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

MERGING ALL THE DATASETS TO MAKE LARGE DATASET ( BEST OF ANALYSIS )

In [ ]:
data = orders.merge(
    order_payments,
    on = ['order_id'],
    how='left'
)

data.shape

(103887, 12)

In [ ]:
data = data.merge(
    order_items,
    on = ['order_id'],
    how='left'
)
data.shape

(118434, 18)

In [ ]:
data = data.merge(
    order_reviews,
    on=['order_id'],
    how='left'
)
data.shape

(119143, 24)

In [ ]:
data = data.merge(
    customers,
    on=['customer_id'],
    how='left'
)
data.shape

(119143, 28)

In [ ]:
data = data.merge(
    products,
    on=['product_id'],
    how='left'

)
data.shape

(119143, 36)

In [ ]:
data = data.merge(
    sellers,
    on=['seller_id'],
    how='left'
)
data.shape

(119143, 39)

In [ ]:
# 1. Clean the geolocation table (one lat/long per zip code)
geo_clean = geolocation.groupby('geolocation_zip_code_prefix').agg({
    'geolocation_lat': 'mean',
    'geolocation_lng': 'mean'
}).reset_index()

# 2. Get Customer Coordinates
data = data.merge(
    geo_clean,
    left_on='customer_zip_code_prefix',
    right_on='geolocation_zip_code_prefix',
    how='left'
).rename(columns={'geolocation_lat': 'customer_lat', 'geolocation_lng': 'customer_lng'})

# 3. Get Seller Coordinates
data = data.merge(
    geo_clean,
    left_on='seller_zip_code_prefix',
    right_on='geolocation_zip_code_prefix',
    how='left'
).rename(columns={'geolocation_lat': 'seller_lat', 'geolocation_lng': 'seller_lng'})

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119143 entries, 0 to 119142
Data columns (total 45 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       119143 non-null  object
 1   customer_id                    119143 non-null  object
 2   order_status                   119143 non-null  object
 3   order_purchase_timestamp       119143 non-null  datetime64[ns]
 4   order_approved_at              119143 non-null  datetime64[ns]
 5   order_delivered_carrier_date   119143 non-null  datetime64[ns]
 6   order_delivered_customer_date  119143 non-null  datetime64[ns]
 7   order_estimated_delivery_date  119143 non-null  datetime64[ns]
 8   payment_sequential             119140 non-null  float64
 9   payment_type                   119140 non-null  object
 10  payment_installments           119140 non-null  float64
 11  payment_value                  119140 non-null  float64
 12  order_item_id                  118310 non-null  float64
 13  product_id                     118310 non-null  object
 14  seller_id                      118310 non-null  object
 15  shipping_limit_date            118310 non-null  datetime64[ns]
 16  price                          118310 non-null  float64
 17  freight_value                  118310 non-null  float64
 18  review_id                      118146 non-null  object
 19  review_score                   118146 non-null  float64
 20  review_comment_title           118146 non-null  object
 21  review_comment_message         118146 non-null  object
 22  review_creation_date           118146 non-null  object
 23  review_answer_timestamp        118146 non-null  object
 24  customer_unique_id             119143 non-null  object
 25  customer_zip_code_prefix       119143 non-null  int64
 26  customer_city                  119143 non-null  object
 27  customer_state                 119143 non-null  object
 28  product_category_name          118310 non-null  object
 29  product_name_length            118310 non-null  float64
 30  product_description_length     118310 non-null  float64
 31  product_photos_qty             118310 non-null  float64
 32  product_weight_g               118310 non-null  float64
 33  product_length_cm              118310 non-null  float64
 34  product_height_cm              118310 non-null  float64
 35  product_width_cm               118310 non-null  float64
 36  seller_zip_code_prefix         118310 non-null  float64
 37  seller_city                    118310 non-null  object
 38  seller_state                   118310 non-null  object
 39  geolocation_zip_code_prefix_x  118821 non-null  float64
 40  customer_lat                   118821 non-null  float64
 41  customer_lng                   118821 non-null  float64
 42  geolocation_zip_code_prefix_y  118045 non-null  float64
 43  seller_lat                     118045 non-null  float64
 44  seller_lng                     118045 non-null  float64
dtypes: datetime64[ns](6), float64(21), int64(1), object(17)
memory usage: 40.9+ MB

In [ ]:
# export csv

data.to_csv('cleaned data.csv', index=False)

#**PHASE 2 ( Feature Engineering )**

In [ ]:
data.shape

(119143, 45)

In [ ]:
AnalysisData = data.copy()

*Droping unnessecarry columns*

In [ ]:
AnalysisData = AnalysisData.drop(columns=["review_comment_title", "review_comment_message", "product_description_length", "product_name_length", ])

In [ ]:
AnalysisData.shape

(119143, 41)

Introducing new features

In [ ]:
# Volume Column as in Brazil volume is used

AnalysisData['Volume_cm3'] = AnalysisData['product_length_cm'] * AnalysisData['product_height_cm'] * AnalysisData['product_width_cm']

In [ ]:
# Weight Scale

def assign_weight_scale(volume_cm3):
    # Standard Brazilian Freight Factor (6000)
    cubed_weight = volume_cm3 / 6000

    if cubed_weight <= 1:
        return 'Light'
    elif cubed_weight <= 5:
        return 'Medium'
    elif cubed_weight <= 15:
        return 'Heavy'
    else:
        return 'Very Heavy'


AnalysisData['weight_scale'] = AnalysisData['Volume_cm3'].apply(assign_weight_scale)

In [ ]:
# Actual days seller takes to dispatch order

dispatch_time_days = (AnalysisData['order_delivered_carrier_date'] - AnalysisData['order_approved_at']).dt
dispatch_time_days = dispatch_time_days.days
AnalysisData['dispatch_time_days'] = dispatch_time_days

In [ ]:
# Actual Carrier time consumed date

carrier_time_days = (AnalysisData['order_delivered_customer_date'] - AnalysisData['order_delivered_carrier_date']).dt
carrier_time_days = carrier_time_days.days
AnalysisData['carrier_time_days'] = carrier_time_days

In [ ]:
# Actual delivery time consumed

delivery_time_days = (AnalysisData['order_delivered_customer_date'] - AnalysisData['order_purchase_timestamp']).dt
delivery_time_days = delivery_time_days.days
AnalysisData['delivery_time_days'] = delivery_time_days

In [ ]:
# Estimated delivery time

order_estimated_delivery_days = (AnalysisData['order_estimated_delivery_date'] - AnalysisData['order_purchase_timestamp']).dt
order_estimated_delivery_days = order_estimated_delivery_days.days
AnalysisData['order_estimated_delivery_days'] = order_estimated_delivery_days

In [ ]:
# Boolean column to check weather delivery was dalayed

order_delayed = AnalysisData['delivery_time_days'] > AnalysisData['order_estimated_delivery_days'].astype(int)
AnalysisData['order_delayed'] = order_delayed

In [ ]:
# Boolean Column to check seller was delayed

seller_delay = AnalysisData['order_delivered_carrier_date'] > AnalysisData['shipping_limit_date']
AnalysisData['seller_delay'] = seller_delay



# converting to int ( 0/1)
AnalysisData['seller_delay'] = AnalysisData['seller_delay'].astype(int)
AnalysisData['seller_delay']

0         0
1         0
2         0
3         0
4         0
         ..
119138    0
119139    0
119140    0
119141    0
119142    0
Name: seller_delay, Length: 119143, dtype: int64

In [ ]:
# Distance in Km

def haversine_distance(lat1, lon1, lat2, lon2):
    # Radius of Earth in kilometers
    r = 6371

    # Convert degrees to radians
    lat1, lon1, lat2, lon2 = map(np.radians, [lat1, lon1, lat2, lon2])

    # Haversine formula
    dlat = lat2 - lat1
    dlon = lon2 - lon1
    a = np.sin(dlat/2)**2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon/2)**2
    c = 2 * np.arcsin(np.sqrt(a))

    return r * c



AnalysisData['distance_km'] = haversine_distance(
    AnalysisData['customer_lat'],
    AnalysisData['customer_lng'],
    AnalysisData['seller_lat'],
    AnalysisData['seller_lng']
)

In [ ]:
# Distance Scale

def assign_distance_scale(dist):
    if dist <= 50:
        return 'Short'
    elif dist <= 500:
        return 'Medium'
    elif dist <= 1500:
        return 'Large'
    else:
        return 'Very Large'

AnalysisData['distance_scale'] = AnalysisData['distance_km'].apply(assign_distance_scale)

In [ ]:
# Total Expense

AnalysisData['total_value'] = AnalysisData['payment_value'] + AnalysisData['freight_value']

In [ ]:
AnalysisData.shape

(119143, 52)

In [ ]:
AnalysisData.head(3)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,payment_sequential,payment_type,...,weight_scale,dispatch_time_days,carrier_time_days,delivery_time_days,order_estimated_delivery_days,order_delayed,seller_delay,distance_km,distance_scale,total_value
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,1.0,credit_card,...,Light,2,6,8,15,False,0,18.57611,Short,26.84
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,3.0,voucher,...,Light,2,6,8,15,False,0,18.57611,Short,10.72
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,2.0,voucher,...,Light,2,6,8,15,False,0,18.57611,Short,27.31

In [ ]:
AnalysisData.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'payment_sequential', 'payment_type', 'payment_installments',
       'payment_value', 'order_item_id', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value', 'review_id',
       'review_score', 'review_creation_date', 'review_answer_timestamp',
       'customer_unique_id', 'customer_zip_code_prefix', 'customer_city',
       'customer_state', 'product_category_name', 'product_photos_qty',
       'product_weight_g', 'product_length_cm', 'product_height_cm',
       'product_width_cm', 'seller_zip_code_prefix', 'seller_city',
       'seller_state', 'geolocation_zip_code_prefix_x', 'customer_lat',
       'customer_lng', 'geolocation_zip_code_prefix_y', 'seller_lat',
       'seller_lng', 'Volume_cm3', 'weight_scale', 'dispatch_time_days',
       'carrier_time_days', 'delivery_time_days',
       'order_estimated_delivery_days', 'order_delayed', 'seller_delay',
       'distance_km', 'distance_scale', 'total_value'],
      dtype='object')

In [ ]:
# export csv

AnalysisData.to_csv('cleaned data.csv', index=False)

#**PHASE 3 ( Selecting features for Analysis )**

In [ ]:
# SINCE WE USED THE JOINS TO MAKE LARGE DATASET THERE WILL BE MULTIPLE DUPLICATES FOR EACH COLUMN
# THE IDEA IS TO EXTRACT COLUMNS WHICH ARE SENSITIVE FOR CERTAIN TASKS
# For example while calucalting total orders we cannot relay on duplicates order id

order_level_bi = AnalysisData.groupby('order_id').agg({
    # --- Existing Columns ---
    'payment_value': 'sum',
    'total_value': 'first',
    'customer_unique_id': 'first',
    'customer_city': 'first',
    'customer_state': 'first',
    'delivery_time_days': 'first',
    'order_estimated_delivery_days': 'first',
    'order_delayed': 'max',
    'review_score': 'mean',
    # --- All Date/Timestamp Columns ---
    'order_purchase_timestamp': 'first',
    'order_approved_at': 'first',
    'order_delivered_carrier_date': 'first',
    'order_delivered_customer_date': 'first',
    'order_estimated_delivery_date': 'first',
    'shipping_limit_date': 'first',
    'review_creation_date': 'first',
    'review_answer_timestamp': 'first'
}).reset_index()

In [ ]:
item_level_bi = AnalysisData[[
    'order_id', 'product_id', 'seller_id',
    'product_category_name', 'price', 'freight_value',
    'payment_type',
    # --- Physical Attributes ---
    'product_weight_g', 'Volume_cm3', 'weight_scale',
    # --- Logistics & Delay Features ---
    'distance_km', 'distance_scale', 'seller_delay',
    'dispatch_time_days', 'carrier_time_days',
    'order_delivered_customer_date', "order_delivered_carrier_date",
    # --- Seller Info ---
    'seller_city', 'seller_state'
]].copy()

In [ ]:
order_level_bi.to_csv('PowerBI_Orders_Master.csv', index=False)

In [ ]:

item_level_bi.to_csv('PowerBI_Items_Logistics.csv', index=False)

Export Successful! All custom engineered features included.

#**PHASE 4 (Visualization)**

We are using PowerBi for data visualization.